require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'beautyshop' do
  use_unimodules!
  config = use_native_modules!
  pod 'instabug-reactnative', :path => '../node_modules/instabug-reactnative'
  use_react_native!(:path => config["reactNativePath"])
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
     if target.name == "React"
        target.remove_from_project
     end
  end
end